rbac/urls.py
# -*- coding: utf-8 -*-
from __future__ import print_function, unicode_literals

urlpatterns = []

rbac/models.py
# -*- coding: utf-8 -*-
from __future__ import print_function, unicode_literals

from datetime import datetime
from logging import getLogger
from queue import Queue

from django.conf import settings
from django.contrib.auth.models import AbstractUser, Permission
from django.core.exceptions import ValidationError
from django.db import connection, models, transaction
from django.db.models import Q
from django.dispatch import receiver
from django.utils.html import format_html
from django.utils.timezone import utc
from django.utils.translation import gettext
from django.utils.translation import gettext_lazy as _

from .deprecation import CallableFalse, CallableTrue

logger = getLogger("rbac.models")


class AbstractBaseModel(models.Model):
    touch_date = models.DateTimeField(editable=False, auto_now=True)
    create_date = models.DateTimeField(editable=False, auto_now_add=True)

    class Meta:
        abstract = True

    def save(self, *args, **kwargs):
        self.full_clean()
        super(AbstractBaseModel, self).save(*args, **kwargs)


class RbacPermission(Permission):
    """
    TODO: Maybe use `from django.contrib.auth.models.Permission` instead.
    """

    class Meta:
        proxy = True
        app_label = 'rbac'
        db_table = 'auth_rbac_permission'
        verbose_name = _("RBAC permission")
        verbose_name_plural = _("RBAC permissions")
        # ordering = [ 'name' ]
        # unique_together = (('content_type', 'name'),)
        # ordering = ('content_type__app_label', 'content_type__model',
        #             'name')


class RbacRoleQuerySet(models.QuerySet):
    def topsorted(self):
        """
        When dumping `RbacRoles` to fixtures you have to take extra care with the foreign key constraints. Since the
        `RbacRole` model references itself through `children`, it is essential that when dumping a role graph the roles
        need to be dumped in the correct order - from "leaf nodes" (roles without children) to top-level roles. This
        method can be used for resolving these dependencies.

        .. important::
           Always use this method when dumping roles as fixtures. Otherwise they might not load.

        .. attention::
           Does *not* return a `QuerySet`!

        :return: An iterable of `RbacRole` objects which is sorted by foreign key dependencies.
        :rtype: iterable
        """
        # This is used for mapping ids to objects
        roles = {}

        """
        A role's children are predecessors of the role when it comes to resolving foreign key dependencies. They
        need to be created first. So when creating a top-sorted list of roles the "leaf" roles (roles without
        children) need to be first in the list.

        Algorithm:

            1. For each role we store their actual parents and the number of children.

               The parents are saved in a dict of sets (`roles_parents[role_pk]`) and the number of children
               for each role are stored in a separate dict (`roles_num_children`)

            2. Then we try to find all roles which do not have any children. We can yield these roles and mark them
               as handled by removing them from `roles_num_children`. Since they are now handled we can notify their
               parents that they have one child less to care about (dependency-wise). We do that by decrementing the
               child counter for each parent.

            3. We do #2 until `roles_num_children` is empty.

        Obviously the algorithm can only come to an end when the role graph is free of circles (which is enforced when
        adding new children).
        """

        roles_num_children = {}
        roles_parents = {}
        max_iterations = 0
        for r in self.iterator():
            max_iterations += 1
            roles[r.pk] = r
            children = set(r.children.values_list('pk', flat=True))
            roles_num_children[r.pk] = len(children)
            for child_pk in children:
                if child_pk not in roles_parents:
                    roles_parents[child_pk] = set()
                roles_parents[child_pk].add(r.pk)

        num_iterations = 0
        while roles_num_children:
            for role_pk, num_children in list(roles_num_children.items()):
                if num_children == 0:
                    yield roles[role_pk]
                    del roles_num_children[role_pk]
                    if role_pk in roles_parents:
                        for parent_pk in roles_parents[role_pk]:
                            roles_num_children[parent_pk] -= 1
                        # roles_parents[role_pk] will never be accessed again
            num_iterations += 1
            # Make sure that we come to an end even if the role queryset does not contain the entire role graph
            # required for top-sorting.
            # In this case still all remaining roles are returned by the for-loop below.
            if num_iterations > max_iterations:
                break

        for pk in roles_num_children:
            yield roles[pk]


class RbacRoleManager(models.Manager):
    """
    Custom manager with support for natural key lookup.
    """
    def get_by_natural_key(self, name):
        return self.get(name=name)


class RbacRole(AbstractBaseModel):
    """
    A role that can be assigned to users and other roles.
    """
    name = models.CharField(max_length=255, db_index=True, unique=True)
    description = models.TextField(blank=True)
    displayName = models.CharField(blank=True, max_length=254, verbose_name=_('Display name'))
    children = models.ManyToManyField( 'self', symmetrical=False, blank=True)
    permissions = models.ManyToManyField(RbacPermission, blank=True)
    children_all = models.ManyToManyField( 'self', symmetrical=False, blank=True, editable=False, through="RbacRoleProfile", related_name="parents_all")

    objects = RbacRoleManager.from_queryset(RbacRoleQuerySet)()

    class Meta:
        app_label = 'rbac'
        db_table = 'auth_rbac_role'
        verbose_name = _("RBAC role")
        verbose_name_plural = _("RBAC roles")
        ordering = [ 'name' ]

    def __init__(self, *args, **kwargs):
        super(RbacRole, self).__init__(*args, **kwargs)

    def __str__(self):
        if self.displayName:
            return self.displayName
        else:
            return self.name

    def _admin_effective_permissions(self):
        return format_html(
            '<a href="./{0}/effective_permissions/">{1}</a>',
            self.pk,
            gettext('Display effective permissions')
        )
    _admin_effective_permissions.allow_tags = True
    _admin_effective_permissions.short_description = _('Effective permissions')

    def _get_all_parents_uncached(self):
        """
        Returns a list of all the parents.

        B{Note:} This method is only used internally and should not be called from outside!

        @returns:   set
        """
        parents = []
        for i in RbacRole.objects.filter( children=self):
            parents.append(i)
            parents.extend(i._get_all_parents_uncached())

        return set(parents)

    def _get_all_children_uncached(self):
        children = []
        for i in self.children.all():
            children.append(i)
            children.extend(i._get_all_children_uncached())
        return set(children)

    def get_all_children(self):
        """
        Returns a QuerySet containing all (direct and indirect) child roles.
        Note: Depends on RbacRoleProfile

        @rtype: QuerySet
        """
        return self.children_all.all()

    def get_direct_children(self):
        """
        @rtype: QuerySet
        """
        return self.children.all()

    def get_all_parents(self):
        """
        Returns a QuerySet containing all (direct and indirect) parent roles.
        Note: Depends on RbacRoleProfile

        @rtype: QuerySet
        """
        return RbacRole.objects.filter(children_all=self)

    def get_direct_parents(self):
        """
        @rtype: QuerySet
        """
        return RbacRole.objects.filter(children=self)

    def natural_key(self):
        return (self.name, )


class RbacRoleProfile(AbstractBaseModel):
    """
    This model acts as a flat role hierarchy and serves as a cache.

    It caches all (direct and indirect) children of a role and can be used for
    both child and parent lookup.
    """
    parent = models.ForeignKey(RbacRole, db_index=True, on_delete=models.CASCADE, related_name="rbacroleprofile_parent")
    child = models.ForeignKey(RbacRole, db_index=True, on_delete=models.CASCADE, related_name="rbacroleprofile_child")

    class Meta:
        app_label = 'rbac'
        db_table = 'auth_rbac_roleprofile'
        unique_together = ('parent', 'child')

    def __str__(self):
        return "%s: %s" % (self.parent, self.child)

    @staticmethod
    def create():
        """
        Creates a new RbacRoleProfile.

        A role profile is a cache which speeds up child/parent lookups for
        roles.
        """
        logger.debug("Creating RbacRoleProfile")
        if settings.USE_TZ:
            currentTime = datetime.utcnow().replace(tzinfo=utc)
        else:
            currentTime = datetime.now()

        adj_list = {}
        bulk_list = []
        pairs = set()

        with transaction.atomic():
            #create an adjacency list of the role hierarchy
            for parent, child in RbacRole.objects.exclude(children=None).values_list('id', 'children'):
                if parent in adj_list:
                    adj_list[parent].append(child)
                else:
                    adj_list[parent]=[child,]

            #Search for all child nodes which can be reached from parent through
            # a breadth-first-search.
            #Instead of coloring we're using a dict which keeps track of the
            # discovered nodes (@see: BFS)
            for parent in adj_list:

rbac/forms.py
# -*- coding: utf-8 -*-
from __future__ import print_function, unicode_literals

from django import forms

from rbac.models import RbacPermissionProfile, RbacRole


class ActiveSessionRoleForm(forms.Form):
    """
    Form for activation/deactivation of roles within a RBAC session.
    """
    active_roles = forms.MultipleChoiceField(
        widget = forms.CheckboxSelectMultiple()
    )

    def __init__(self, session, *args, **kwargs):
        """
        @raise AttributeError: When instance was not specified.
        @raise TypeError: When instance is not valid.
        """
        self.session = session
        valid_roles = session.user.get_all_roles()
        super(ActiveSessionRoleForm, self).__init__(*args, **kwargs)
        self.fields['active_roles'].choices = valid_roles.values_list('pk', 'name')
        self.fields['active_roles'].initial = self.session.get_active_role_ids()

    def clean_active_roles(self):
        return self.session.user.get_all_roles().filter(id__in=self.cleaned_data['active_roles'])

    def save(self, *args, **kwargs):
        self.session.active_roles = self.cleaned_data['active_roles']
        self.session.save()
        return self.session


def _get_app_label_choices():
    app_labels = RbacPermissionProfile.objects.all().values_list(
                    'permission__content_type__app_label',
                    flat=True
                 ).distinct()
    choices = [('', '---------')]
    choices.extend([(i,i) for i in app_labels])
    return choices

def _get_model_choices():
    models = RbacPermissionProfile.objects.all().values_list(
                 'permission__content_type__model',
                 flat=True
             ).distinct()
    choices = [('', '---------')]
    choices.extend([(i,i) for i in models])
    return choices

class EffectivePermissionFilterForm(forms.Form):
    app_label = forms.ChoiceField(label="App", required=False, choices=_get_app_label_choices)
    model = forms.ChoiceField(label="Model", required=False, choices=_get_model_choices)


class RbacRoleForm(forms.ModelForm):
    """
    This form is displayed in the Django admin page for modifying RBAC roles.
    """

    class Meta:
        model = RbacRole
        exclude = ('children_all', )


    def __init__(self, *args, **kwargs):
        super(RbacRoleForm, self).__init__(*args, **kwargs)
        #filter out invalid choices for children
        if self.instance:
            exclude_ids = [self.instance.id, ]
            for parent in self.instance.get_all_parents():
                exclude_ids.append(parent.id)
            self.fields['children'].queryset = RbacRole.objects.exclude(pk__in=exclude_ids)


    def clean_children(self):
        for child_role in self.cleaned_data['children']:
            if self.instance == child_role:
                raise forms.ValidationError("Adding this child role would result in a cycle in the role graph!")

            if child_role in self.instance.get_all_parents():
                raise forms.ValidationError("Adding this child role would result in a cycle in the role graph!")
        return self.cleaned_data['children']

rbac/templates/rbac/admin_effective_permissions.html
{% extends "admin/base_site.html" %}
{% load i18n %}

{% block title %}Effective permissions of RBAC role{% endblock %}
{% block extrastyle %}
<script type="text/javascript" src="{{STATIC_URL}}admin/js/vendor/jquery/jquery.js"></script>
{% endblock %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
&rsaquo; <a href="{% url 'admin:app_list' app_label='rbac' %}">RBAC</a>
&rsaquo; <a href="{% url 'admin:rbac_rbacrole_changelist' %}">RBAC Roles</a>
&rsaquo; <a href="{% url 'admin:rbac_rbacrole_change' role.id %}">Role &quot;{{role.name}}&quot;</a>
&rsaquo; {% trans "Effective permissions" %}
</div>
{% endblock %}

{% block extrahead %}
 {{ block.super }}
 <link rel="stylesheet" type="text/css" href="{{STATIC_URL}}admin/css/forms.css" />
{% endblock %}

{% block content %}
<h1>{% blocktrans with role_name=role.name %}Effective permissions of role &quot;{{role_name}}&quot;{% endblocktrans %}</h1>
<form action="." method="post" id="id_effectivepermissionfilterform" style="visibility: hidden;">
  {% csrf_token %}
  <fieldset class="module aligned">
    <h2>Filter</h2>
    <div class="form-row field-name">
    	<div>
    		<label for="id_app_label">App-Label:</label>
    		<select id="id_app_label" name="app_label"></select>
    	</div>
    </div>
    <div class="form-row field-name">
    	<div>
    		<label for="id_model">Model:</label>
    		<select id="id_model" name="model"></select>
    	</div>
    </div>
  </fieldset>
</form>

<table id="id_permission_table">
 <tr>
  <th>App</th>
  <th>Model</th>
  <th>Operation</th>
 </tr>
</table>

<script>
	permissions = {{permissions}};

	function getEmptyOption() {
		return $("<option/>").val('').text('---------');
	}
 
	function setAppLabelChoices() {
    	$('select#id_app_label').empty();
    	getEmptyOption().appendTo("select#id_app_label");
    	for (var app_label in permissions) {
			$("<option/>").val(app_label).text(app_label).appendTo('select#id_app_label');
		}
	}
 
	function setModelChoices() {
		var app_label = $("select#id_app_label").val();
		$("select#id_model").empty();
		getEmptyOption().appendTo("select#id_model");
		
		if (permissions[app_label]) {
			for (var model in permissions[app_label]) {
				$("<option/>").val(model).text(model).appendTo("select#id_model");
			}
		} else {
			for (var app_label in permissions) {
				for (var model in permissions[app_label]) {
					$("<option/>").val(model).text(model).appendTo("select#id_model");
				}
			}
		}
	}

	/**
	 * Add a record for all permissions of the specified app_label, model
	 * combinations to the permission table. 
	 */
	function addPermissionsToTable(app_label, model) {
		for (var i=0;i<permissions[app_label][model].length;++i) {
			entry = "<tr class=\"permission_record\"><td>"+app_label+"</td><td>"+model+"</td><td>"+permissions[app_label][model][i]+"</td></tr>";
			$("table#id_permission_table").append(entry);
		}
	}

	/**
	 * Rebuilds the HTML permission table based on the values specified by the
	 * filter form.
	 */
	function buildTable() {
		$("tr.permission_record").remove();
		var app_label = $("select#id_app_label").val();
		var model = $("select#id_model").val();
		var permission;
		var entry;
		
		if (app_label == '') {
			if (model == '') {
				for (app_label in permissions) {
					for (model in permissions[app_label]) {
						addPermissionsToTable(app_label, model);
					}
				}
			} else {
				for (app_label in permissions) {
					for (var i in permissions[app_label]) {
						if (i==model) {
							addPermissionsToTable(app_label, model);
						}
					}
				}
			}
		} else {
			if (permissions[app_label][model]) {
				addPermissionsToTable(app_label, model);
			} else {
				for (model in permissions[app_label]) {
					addPermissionsToTable(app_label, model);
				}
			}
		}
	}
 
 $(document).ready(function() {
     $('select#id_app_label').bind('change', function(){
            setModelChoices();
            buildTable();
      });
     $('select#id_model').bind('change', function(){
            buildTable();
      });
     setAppLabelChoices();
     setModelChoices();
     buildTable();
     $("form#id_effectivepermissionfilterform").css("visibility", "visible");

 });
</script>


{% endblock content %}

rbac/templates/rbac/admin_model_permissions.html
{% extends "admin/base_site.html" %}
{% load i18n %}

{% block title %}{% trans "Permissions by model" %}{% endblock %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
&rsaquo; <a href="{% url 'admin:app_list' app_label='rbac' %}">{% trans "RBAC" %}</a>
&rsaquo; <a href="{% url 'admin:rbac_rbacrole_changelist' %}">{% trans "RBAC Roles" %}</a>
&rsaquo; {% trans "Permissions by model" %}
</div>
{% endblock %}

{% block content %}
<h1>{% trans "Permissions by model" %}</h1>

<p>{% blocktrans %}The following table provides an overview of the model permissions which are currently assigned to roles.{% endblocktrans %}</p>

<table>
 <thead>
  <tr>
   <th>{% trans "Permission" %}</th>
   <th>{% trans "RBAC Roles" %}</th>
  </tr>
 </thead>
 <tbody>
 {% for contenttype, permissions in permissions_by_ctype.items %}
  <tr>
   <td colspan=2 style="font-weight:bold;background-color:#CDCDCD;">{{contenttype.app_label}}.{{contenttype.model}} ({{contenttype}})</td>
  </tr>
  {% for perm in permissions %}
  <tr>
   <td>{{perm.name}}</td>
   <td>{{perm.rbacrole_set.all|join:", "}}</td>
  </tr>
   {% endfor %}
 {% endfor %}
 </tbody>
</table>

{% endblock content %}

rbac/templates/rbac/change_form.html
{% extends "admin/change_form.html" %}
{% load i18n %}

{% block object-tools-items %}
 <li><a href="./effective_permissions/">{% trans "Effective permissions" %}</a></li>
 {{block.super}}
{% endblock %}

rbac/templates/rbac/change_list.html
{% extends "admin/change_list.html" %}
{% load i18n %}

{% block object-tools-items %}
 <li><a href="{% url "admin:rbac_rbacrole_permissions_by_model" %}">{% trans "Model permissions" %}</a></li>
 {{block.super}}
{% endblock %}

rbac/templates/rbac/set_active_roles.html
{% extends "admin/base.html" %}
{% load static i18n %}
{% block stylesheet %}{% static "rbac/css/base.css" %}{% endblock %}

{% block title %}{% trans 'Select RBAC session roles' %}{% endblock %}

{% block branding %}
<h1 id="site-name">{% trans 'Select RBAC session roles' %}</h1>
{% endblock %}

{% block bodyclass %}rbacroles{% endblock %}

{% block content_title %}{% endblock %}

{% block userlinks %}{% endblock %}

{% block breadcrumbs %}{% endblock %}

{% block content %}

{% if form.non_field_errors %}
{% for error in form.non_field_errors|add:form.errors %}
<p class="errornote">
    {{ error }}
</p>
{% endfor %}
{% endif %}

<div id="content-main">
<form action="." method="post">{% csrf_token %}
    {% if form.active_roles.errors %}{{ form.active_roles.errors }}{% endif %}
    <p>{% trans 'Please select one or more roles for this session:' %}</p>
    {{ form.active_roles }}

  <div class="rbac-submit-row">
    <input type="submit" name="cancel" value="{% trans 'Cancel' %}" />
    <input type="submit" name="submit" class="default" value="{% trans 'Apply' %}" />
  </div>
</form>
</div>
{% endblock %}